# Generated by Django 4.2.10 on 2024-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0006_register_user_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='register_user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
