# Generated by Django 4.2.10 on 2024-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0007_register_user_email_alter_register_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
