# Generated by Django 4.2.10 on 2024-02-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0008_order_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='id',
        ),
        migrations.AlterField(
            model_name='register_user',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
