# Generated by Django 4.2.10 on 2024-03-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0009_remove_register_user_id_alter_register_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quality',
        ),
    ]
