# Generated by Django 4.2.10 on 2024-03-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0010_remove_order_finish_remove_order_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='sampling_stock',
            fields=[
                ('designid', models.CharField(default='Design_ID_Not_Provided', max_length=100, primary_key=True, serialize=False)),
                ('rackno', models.IntegerField(max_length=10)),
                ('quantity', models.IntegerField(max_length=10)),
            ],
        ),
    ]
