# Generated by Django 4.2.10 on 2024-03-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0011_sampling_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='orderno',
            field=models.IntegerField(default=1000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampling_stock',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sampling_stock',
            name='rackno',
            field=models.IntegerField(),
        ),
    ]
