# Generated by Django 4.2.10 on 2024-03-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0016_alter_order_selected_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='selected_samples',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
