# Generated by Django 4.2.10 on 2024-03-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0017_alter_order_selected_samples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='selected_samples',
        ),
    ]
