# Generated by Django 4.2.10 on 2024-03-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0019_order_selected_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(default='No-Name', max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
