# Generated by Django 4.2.10 on 2024-03-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0020_designs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designs',
            name='image',
            field=models.ImageField(upload_to='designs/'),
        ),
    ]
