# Generated by Django 4.2.10 on 2024-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0023_alter_register_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sample_type',
            new_name='sampletype',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='No Address Found', max_length=150),
            preserve_default=False,
        ),
    ]
