# Generated by Django 4.2.10 on 2024-03-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0024_rename_sample_type_order_sampletype_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
