# Generated by Django 4.2.10 on 2024-04-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0025_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulk_Order',
            fields=[
                ('orderno', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('selected_samples', models.CharField(max_length=800, null=True)),
                ('completestatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='brand',
        ),
        migrations.AddField(
            model_name='designs',
            name='GSM',
            field=models.CharField(default='No-GSM', max_length=50),
        ),
        migrations.AddField(
            model_name='designs',
            name='fabric_type',
            field=models.CharField(default='No-Fabric Type', max_length=50),
        ),
        migrations.AddField(
            model_name='designs',
            name='finish',
            field=models.CharField(default='No-Finish', max_length=80),
        ),
        migrations.AddField(
            model_name='designs',
            name='pick',
            field=models.CharField(default='No-Pick', max_length=50),
        ),
        migrations.AddField(
            model_name='designs',
            name='shade_color',
            field=models.CharField(default='No-Shade', max_length=100),
        ),
        migrations.AddField(
            model_name='designs',
            name='weave',
            field=models.CharField(default='No-Weave', max_length=50),
        ),
        migrations.AddField(
            model_name='designs',
            name='width',
            field=models.CharField(default='No-Width', max_length=50),
        ),
    ]
