# Generated by Django 4.2.10 on 2024-04-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0028_bulk_order_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulk_order',
            old_name='imageurl',
            new_name='image',
        ),
    ]
