# Generated by Django 4.2.10 on 2024-04-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0029_rename_imageurl_bulk_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk_order',
            name='image',
            field=models.ImageField(default='/None/', max_length=150, upload_to=''),
        ),
    ]
